# Project Information
site_name: NCKUME Wiki
site_description: NCKUME Wiki 為機械工程領域整理有價值的知識和資訊。注重與實際工程問題的相關性、應用價值，幫助學習者在學習、面試及工作上取得成功。
site_author: NCKUME Wiki Team
site_url: https://NCKUME-wiki.org
strict: false

# Repository
repo_name: NCKUME-wiki/NCKUME-wiki
repo_url: https://github.com/NCKUME-wiki/NCKUME-wiki
edit_uri: https://NCKUME-wiki.org/edit-landing/?ref=

# Copyright
copyright: Copyright &copy; 2024-2025 NCKUME Wiki Team

# Contents
nav:
  - 簡介: 
    - Getting Started: index.md # trans done
    - 關於本項目: intro/about.md
    - 如何參與: intro/htc.md
    - NCKUME Wiki 不是什麼: intro/what-nckume-wiki-is-not.md
    - 格式手冊: intro/format.md
    - 數學符號表: intro/symbol.md
    - F.A.Q.: intro/faq.md
    # - 鏡像站列表: intro/mirrors.md # 我們還沒有那麼有錢買得起那麼多網域。
    - 致謝: intro/thanks.md #
  - 總論:
    - 機械工程: general/index.md
    # - 電腦輔助設計: general/CAD.md
    - 量測: general/metrology.md
    - 工程圖:  general/eng-drawing.md
    - 機動學: general/mechanism.md
    - 振動學: general/vibration.md
  - 工程數學:
    - 簡介: eng-math/index.md
    - 微積分: eng-math/calculus.md
    - 線性代數: eng-math/linear-algbra.md
    - 常微分方程: eng-math/ode.md
    - 偏微分方程: eng-math/pde.md
    - 複分析: eng-math/complex.md
    - 張量: eng-math/tensor.md
    - 統計: eng-math/statistics.md
  - 工程力學:
    - 簡介: mechanics/index.md
    - 靜力學: mechanics/statics.md
    - 動力學: mechanics/dynamics.md
    - 運動學: mechanics/kinematics.md
    - 材料力學: mechanics/material.md
    - 彈性力學: mechanics/elasticity.md
    - 塑性力學: mechanics/plasticity.md
  - 熱流科學:
    - 簡介: thermo-fluid/index.md
    - 熱力:  thermo-fluid/thermodynamics.md
    - 熱傳: thermo-fluid/heat-transfer.md
    - 流體力學: thermo-fluid/fluid.md
    - 燃燒學: thermo-fluid/combustion.md
  - 光電磁學: 
    - 簡介: oem/index.md
    - 光學: oem/optics.md
    - 電子學: oem/electronics.md
    - 電工學: oem/electrical-eng.md
    - 機電系統: oem/electromechanical.md
  - 控制理論:
    - 簡介: control/index.md
    - 控制理論: control/theory.md
    - 機器人學: control/robotics.md
    - 控制工具: control/tools.md
  - 材料科學:
    - 簡介: material/index.md
    - 材料結構: material/struct.md
    - 材料試驗: material/test.md
    - 工程材料: 
      - 金屬: material/metal.md
      - 陶瓷: material/ceramics.md
      - 聚合物: material/polymer.md
      - 複合材料: material/composite.md
  - 機械製造:
    - 機械製造: manufacture/index.md
  - 機械設計:
    - 機械設計: design/index.md
  - 電腦輔助X:
    - 電腦輔助工程: computer-aided/index.md # CAE
    - 設計: computer-aided/CAD.md
    - 製造: computer-aided/CAM.md
    - 產品生命週期管理: computer-aided/PLM.md
  - 其他:
    - 其他: misc/index.md
    - 統計製程管理: misc/spc.md
    - 品質工程: misc/quality.md
    - 可靠度工程: misc/reliability.md
    - 數值方法: misc/numeric-method.md
  - 術語列表:
    - glossary: glossary/index.md
  - 專題:
    - Make your X: 404.html
  - 測試: basic/insertion-sort.md


# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh-TW'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'media/NCKUME_favicon_250201.ico'
  icon:
    logo: 'NCKUME/NCKUME-wiki'
    # logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins: []
  # - search

hooks:
  - hooks/on_env.py
  - hooks/on_page_markdown.py

# Customization
extra:
  disqus: 'NCKUME-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  analytics:
    provider: google
    property: ---
  alternate:
    - link: / #/macro/
      name: 繁中-Elaborated Chinese
    - link: /micro/ # /micro/
      name: 簡中-Succinct Chinese
    - link: /en/
      name: English

extra_javascript:
  - '_static/js/ToggleEnTerm.js'
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'
  # - '{OIWikiFeedbackSystemFrontendJS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts # 不知道什麼東西
  # - '{OIWikiFeedbackSystemFrontendContentScript}' # see: scripts/pre-build/install-feedback-sys-frontend.ts

extra_css:
  - '_static/css/extra.css?v=16'
  - '_static/css/translationBtn.css'
  # - '_static/css/offset-inject-debug.css'
  # - '{OIWikiFeedbackSystemFrontendCSS}' # see: scripts/pre-build/install-feedback-sys-frontend.ts

# Extensions
markdown_extensions:
  # - document-offsets-injection:
  #     # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
