[build]
  base = "scripts/" # Trick to disable dependencies installation
  command = "cd .. && scripts/netlify/build.sh"  # add permission

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.10"
